// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package com.baidu.jprotobuf.pbrpc.proto;

public final class EchoInfoClass {
    private EchoInfoClass() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface EchoInfoOrBuilder extends com.google.protobuf.MessageOrBuilder {

        // required string message = 1;
        /**
         * <code>required string message = 1;</code>
         */
        boolean hasMessage();

        /**
         * <code>required string message = 1;</code>
         */
        java.lang.String getMessage();

        /**
         * <code>required string message = 1;</code>
         */
        com.google.protobuf.ByteString getMessageBytes();
    }

    /**
     * Protobuf type {@code pkg.EchoInfo}
     */
    public static final class EchoInfo extends com.google.protobuf.GeneratedMessage implements EchoInfoOrBuilder {
        // Use EchoInfo.newBuilder() to construct.
        private EchoInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private EchoInfo(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final EchoInfo defaultInstance;

        public static EchoInfo getDefaultInstance() {
            return defaultInstance;
        }

        public EchoInfo getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private EchoInfo(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        bitField0_ |= 0x00000001;
                        message_ = input.readBytes();
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.internal_static_pkg_EchoInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.internal_static_pkg_EchoInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.class,
                            com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.Builder.class);
        }

        public static com.google.protobuf.Parser<EchoInfo> PARSER = new com.google.protobuf.AbstractParser<EchoInfo>() {
            public EchoInfo parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
                return new EchoInfo(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<EchoInfo> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required string message = 1;
        public static final int MESSAGE_FIELD_NUMBER = 1;
        private java.lang.Object message_;

        /**
         * <code>required string message = 1;</code>
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string message = 1;</code>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string message = 1;</code>
         */
        public com.google.protobuf.ByteString getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            message_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            if (!hasMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(
            com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseDelimitedFrom(
            java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code pkg.EchoInfo}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.internal_static_pkg_EchoInfo_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.internal_static_pkg_EchoInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.class,
                                com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.Builder.class);
            }

            // Construct using
            // com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.internal_static_pkg_EchoInfo_descriptor;
            }

            public com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo getDefaultInstanceForType() {
                return com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.getDefaultInstance();
            }

            public com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo build() {
                com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo buildPartial() {
                com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo result;
                result = new com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo(
                        this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo) {
                    return mergeFrom((com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo other) {
                if (other == com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo.getDefaultInstance())
                    return this;
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000001;
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMessage()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.baidu.jprotobuf.pbrpc.proto.EchoInfoClass.EchoInfo) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required string message = 1;
            private java.lang.Object message_ = "";

            /**
             * <code>required string message = 1;</code>
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string message = 1;</code>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string message = 1;</code>
             */
            public com.google.protobuf.ByteString getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string message = 1;</code>
             */
            public Builder setMessage(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string message = 1;</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000001);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>required string message = 1;</code>
             */
            public Builder setMessageBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                message_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:pkg.EchoInfo)
        }

        static {
            defaultInstance = new EchoInfo(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:pkg.EchoInfo)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_pkg_EchoInfo_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_pkg_EchoInfo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\necho.proto\022\003pkg\"\033\n\010EchoInfo\022\017\n\007message"
                + "\030\001 \002(\tB0\n\037com.baidu.jprotobuf.pbrpc.prot" + "oB\rEchoInfoClass" };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner;
        assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_pkg_EchoInfo_descriptor = getDescriptor().getMessageTypes().get(0);
                internal_static_pkg_EchoInfo_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_pkg_EchoInfo_descriptor, new java.lang.String[] { "Message", });
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
